theme: osuny
_merge: deep
enableRobotsTXT: true
removePathAccents: true
params:
  debug:
    productionUrl: "https://transitiondesign.labo.cyu.fr"
  home:
    head:
      title: site
  summary:
    position: hero
  search:
    active: false
  default:
    single:
      taxonomies:
        show_name: false