theme: osuny
_merge: deep
enableRobotsTXT: true
removePathAccents: true
params:
  home:
    head:
      title: site
  summary:
    position: hero
  search:
    active: false
  default:
    single:
      taxonomies:
        display: false